#!/bin/bash

DIR=$(dirname $(realpath $0))
RISCV="/homelocal/luiscrespo/RISCV"

GENERATOR=Ninja
FASTER_COMPILATION="-DBUILD_SHARED_LIBS=True -DLLVM_USE_SPLIT_DWARF=True -DLLVM_OPTIMIZED_TABLEGEN=True -DLLVM_BUILD_TESTS=False"
TARGETS="RISCV"
DEFAULT_TARGET_TRIPLE="riscv64-unknown-elf"
PROJECTS="clang;clang-tools-extra;lld"
RPROJECTS="libcxx;libcxxabi;libunwind;libc;compiler-rt"
DEFAULT_SYSROOT="${RISCV}/riscv64-unknown-elf"
GCC_INSTALL_PREFIX="${RISCV}"
#DCMAKE_INSTALL_PREFIX

PROJECT_ROOT="${DIR}/llvm-project/llvm"
BUILD_ROOT="${DIR}/llvm-project/buildRISCV"

cd $PROJECT_ROOT
mkdir $BUILD_ROOT
cd $BUILD_ROOT

cmake -G $GENERATOR -DCMAKE_BUILD_TYPE="Debug" -DLLVM_ENABLE_ASSERTIONS=On \
        -DCOMPILER_RT_BAREMETAL_BUILD=ON \
        -DCOMPILER_RT_DEFAULT_TARGET_ONLY=ON \
        $FASTER_COMPILATION -DDEFAULT_SYSROOT=$DEFAULT_SYSROOT \
        -DGCC_INSTALL_PREFIX=$GCC_INSTALL_PREFIX \
        -DLLVM_TARGETS_TO_BUILD=$TARGETS -DLLVM_ENABLE_PROJECTS=$PROJECTS \
        -DLLVM_ENABLE_RUNTIMES=$RPROJECTS \
        -DLLVM_DEFAULT_TARGET_TRIPLE=$DEFAULT_TARGET_TRIPLE $PROJECT_ROOT

cmake --build .